# Generated by Django 3.2.8 on 2021-10-07 10:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Peak',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('lat', models.DecimalField(decimal_places=8, max_digits=8,
                                            validators=[django.core.validators.MinValueValidator(-90),
                                                        django.core.validators.MaxValueValidator(90)])),
                ('lon', models.DecimalField(decimal_places=8, max_digits=8,
                                            validators=[django.core.validators.MinValueValidator(-180),
                                                        django.core.validators.MaxValueValidator(180)])),
                ('altitude', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
