# Generated by Django 3.2.8 on 2021-10-08 05:54

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0002_rename_lon_peak_long'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='lat',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-90),
                                                django.core.validators.MaxValueValidator(90)]),
        ),
        migrations.AlterField(
            model_name='peak',
            name='long',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(-180),
                                                django.core.validators.MaxValueValidator(180)]),
        ),
    ]
