# Generated by Django 3.2.8 on 2021-10-08 09:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0003_auto_20211008_0554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
