# Generated by Django 3.2.8 on 2021-10-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_peak_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='peak',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
