# Generated by Django 3.2.8 on 2021-10-10 19:04

from api.models import Peak
from django.db import migrations


def insert_first_peak(apps, schema_editor):
    insertion = Peak(
        name="Pic du Midi de Bigorre",
        altitude=0,
        lat=42.9363889,
        long=0.14277778
    )
    insertion.save()


class Migration(migrations.Migration):
    dependencies = [
        ('api', '0006_alter_peak_id'),
    ]

    operations = [
        migrations.RunPython(insert_first_peak),
    ]
