# Generated by Django 3.2.8 on 2021-10-11 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20211010_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='AllowCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('code', models.CharField(max_length=2)),
            ],
        ),
    ]
